version: "3.9"

services:
  web:
    build: .
    command: gunicorn tekon_website.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: tekon_website.settings
      PYTHONUNBUFFERED: "1"
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-tekon-rl.cl,redlinegs.com,localhost}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8002:8000"

volumes:
  static_volume:
  media_volume:
